# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Plugins
version:      0.3
version_from: lib/Plugins.pm
installdirs:  site
requires:
    Carp:                          0
    Hash::Util:                    0
    UNIVERSAL:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
